FarmHeroes/Web/FarmHeroes.Web/Controllers/ChatController.cs
namespace FarmHeroes.Web.Controllers
{
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.ViewModels.ChatModels;
    using FarmHeroes.Web.ViewModels.NotificationModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    [Authorize]
    public class ChatController : BaseController
    {
        private readonly IChatService chatService;

        public ChatController(IChatService chatService)
        {
            this.chatService = chatService;
        }

        public async Task<IActionResult> Index()
        {
            ChatViewModel viewModel = await this.chatService.GetAllMessagesToViewModel();
            return this.View(viewModel);
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Controllers/DungeonController.cs
namespace FarmHeroes.Web.Controllers
{
    using System.Threading.Tasks;

    using FarmHeroes.Data.Models.Enums;
    using FarmHeroes.Services.Data.Constants;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.Filters;
    using FarmHeroes.Web.ViewModels.DungeonModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    [LevelRequirement(RequiredLevels.DungeonRequiredLevel)]
    public class DungeonController : BaseController
    {
        private readonly IDungeonService dungeonService;

        public DungeonController(IDungeonService dungeonService)
        {
            this.dungeonService = dungeonService;
        }

        public async Task<IActionResult> Index()
        {
            DungeonIndexViewModel viewModel = await this.dungeonService.GetDungeonViewModel<DungeonIndexViewModel>();

            if (viewModel.WorkStatus == WorkStatus.Dungeon || viewModel.WorkStatus == WorkStatus.DungeonIdle)
            {
                return this.RedirectToAction("Walking");
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> Walking()
        {
            DungeonWalkingViewModel viewModel = await this.dungeonService.GetDungeonViewModel<DungeonWalkingViewModel>();

            if (viewModel.ChronometerWorkUntil == null)
            {
                return this.RedirectToAction("Index");
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> BuyKey()
        {
            await this.dungeonService.BuyKey();

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Enter()
        {
            await this.dungeonService.StartDungeon();

            return this.RedirectToAction("Walking");
        }

        public async Task<IActionResult> NextFloor()
        {
            await this.dungeonService.GoToNextFloor();

            return this.RedirectToAction("Walking");
        }

        public async Task<IActionResult> WalkOnFloor()
        {
            await this.dungeonService.WalkOnFloor();

            return this.RedirectToAction("Walking");
        }

        public async Task<IActionResult> Exit()
        {
            await this.dungeonService.EndDungeon();

            return this.RedirectToAction("Index");
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Controllers/HeroController.cs
namespace FarmHeroes.Web.Controllers
{
    using System.Threading.Tasks;

    using AutoMapper;
    using FarmHeroes.Data;
    using FarmHeroes.Data.Models;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.Filters;
    using FarmHeroes.Web.ViewModels.HeroModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class HeroController : BaseController
    {
        private readonly IHeroService heroService;
        private readonly IUserService userService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly FarmHeroesDbContext context;

        public HeroController(IHeroService heroService, IUserService userService, UserManager<ApplicationUser> userManager, FarmHeroesDbContext context)
        {
            this.heroService = heroService;
            this.userService = userService;
            this.userManager = userManager;
            this.context = context;
        }

        public async Task<IActionResult> Index()
        {
            HeroOverviewViewModel viewModel = await this.heroService.GetCurrentHeroViewModel<HeroOverviewViewModel>();

            if (viewModel == null)
            {
                return this.Redirect("/Hero/Create");
            }

            return this.View(viewModel);
        }

        [Route("/Hero/{id}")]
        public async Task<IActionResult> Hero(int id)
        {
            HeroViewModel viewModel = await this.heroService.GetHeroViewModelById<HeroViewModel>(id);

            return this.View(viewModel);
        }

        public async Task<IActionResult> Create()
        {
            if (await this.userService.CurrentUserHasHero())
            {
                return this.Redirect("/Hero");
            }

            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(HeroCreateInputModel inputModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect("/Hero/Create");
            }

            await this.heroService.CreateHero(inputModel);

            return this.Redirect("/Hero");
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Controllers/NewsController.cs
namespace FarmHeroes.Web.Controllers
{
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.ViewModels.NewsModels;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    public class NewsController : BaseController
    {
        private readonly INewsService newsService;

        public NewsController(INewsService newsService)
        {
            this.newsService = newsService;
        }

        public async Task<IActionResult> Index()
        {
            NewsListViewModel[] viewModel = await this.newsService.GetAllNews<NewsListViewModel>();

            return this.View(viewModel);
        }

        public async Task<IActionResult> Details(int id)
        {
            NewsDetailsViewModel viewModel = await this.newsService.GetNewsModelById<NewsDetailsViewModel>(id);

            return this.View(viewModel);
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Views/Shared/_EquipmentViewModelPartiallView.cshtml
@model FarmHeroes.Web.ViewModels.EquipmentModels.EquipmentViewModel

@if (Model != null)
{
    <div class="position-relative equipment-box m-2">
        <img src="@Model.ImageUrl" alt="item" class="img-fluid d-block mr-auto ml-auto mb-1 item-image" data-toggle="tooltip" data-placement="left" title="@SharedLocalizer.EquipmentLocalizer(Model.Name)<br><img src='/images/icons/level-icon.png' class='icon'>: @Model.Level @if (Model.Attack != 0) {<br><span><img src='/images/icons/attack-icon.png' class='icon'>: @Model.Attack</span>}@if (Model.Defense != 0) {<br><span><img src='/images/icons/defense-icon.png' class='icon'>: @Model.Defense</span>}@if (Model.Mastery != 0) {<br><span><img src='/images/icons/mastery-icon.png' class='icon'>: @Model.Mastery</span>}@if (Model.Dexterity != 0) {<br><span><img src='/images/icons/dexterity-icon.png' class='icon'>: @Model.Dexterity</span>}">
    </div>
}
else
{
    <img src="~/images/equipment/blank.png" alt="item" class="img-fluid d-block mr-auto ml-auto mb-1 item-image" />
}

FarmHeroes/Web/FarmHeroes.Web/Views/Shared/_GuestLayout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet

@using FarmHeroes.Common

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/custom.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animations.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/superhero/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/custom.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animations.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand d-lg-block d-md-none" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Navbar-Home"]</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="News" asp-action="Index">@Localizer["Navbar-News"]</a>
                </li>
            </ul>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />
    @RenderBody()
    <hr class="bg-primary">
    <footer>
        <div class="row">
            <div class="col-10 text-left">
                <h6 class="font-weight-bold">@Localizer["Created-By"] <a href="https://softuni.bg/users/profile/show/peterarnaudov" target="_blank">PeterArnaudov</a>.</h6>
                <div>
                    <a href="https://www.instagram.com/peterxarnaudov/" target="_blank"><img src="~/images/community/instagram.png" alt="Instagram logo" class="m-2 logo"></a>
                    <a href="https://www.facebook.com/Peter.P.Arnaudov" target="_blank"><img src="~/images/community/facebook.png" alt="Facebook logo" class="m-2 logo"></a>
                    <a href="https://www.linkedin.com/in/peter-arnaudov/" target="_blank"><img src="~/images/community/linkedin.png" alt="LinkedIn logo" class="m-2 logo"></a>
                    <a href="https://github.com/PeterArnaudov/FarmHeroes" target="_blank"><img src="~/images/community/github.png" alt="Github logo" class="m-2 logo"></a>
                </div>
                <h6 class="font-weight-bold">@Localizer["Educational-Purpose"] <a href="https://www.botva.ru">www.botva.ru</a>.</h6>
            </div>
            <div class="col-2">
                <div class="form-group">
                    <select id="change-language" class="form-control" name="culture" onchange="changeLanguage()">
                        <option selected>@Localizer["Choose-Language"]</option>
                        <option value="en">@Localizer["English"]</option>
                        <option value="bg">@Localizer["Bulgarian"]</option>
                    </select>
                </div>
            </div>
        </div>
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>

FarmHeroes/Web/FarmHeroes.Web/Views/Shared/_LoggedLayout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
@inject FarmHeroes.Services.Data.Contracts.ILevelService LevelService

@using FarmHeroes.Services.Data.Constants
@using FarmHeroes.Common

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/custom.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animations.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/sun-moon.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    <environment names="Staging,Production">
        <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.4.1/superhero/bootstrap.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/custom.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/animations.css" rel="stylesheet" asp-append-version="true" />
        <link href="~/css/sun-moon.css" rel="stylesheet" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    @if (DateTime.UtcNow.Hour < 7 || DateTime.UtcNow.Hour > 18)
    {
        <div class="cloud"></div>
        <div class="moon"></div>
    }
    else
    {
        <div class="sun">
            <div class="ray_box">
                <div class="ray ray1"></div>
                <div class="ray ray2"></div>
                <div class="ray ray3"></div>
                <div class="ray ray4"></div>
                <div class="ray ray5"></div>
                <div class="ray ray6"></div>
                <div class="ray ray7"></div>
                <div class="ray ray8"></div>
                <div class="ray ray9"></div>
                <div class="ray ray10"></div>
            </div>
        </div>
    }
    <div class="wrapper container">
        <div class="text-center">
            <a asp-area="" asp-controller="News" asp-action="Index" class="small">@Localizer["Navbar-News"]</a> |
            <a asp-area="" asp-controller="Chat" asp-action="Index" class="small">@Localizer["Navbar-Chat"]</a> |
            @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
            {
                <a class="small" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">@Localizer["Navbar-Administration"]</a> @: |
            }
            <a class="small" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">@Localizer["Navbar-Settings"]</a>
        </div>
        <div class="mt-1 row text-center p-2">
            <h2 class="col-lg-3 d-lg-block d-none m-auto">Farm Heroes</h2>
            <button class="navbar-toggler btn-outline-primary text-white col-3 d-lg-none d-md-block text-uppercase" aria-pressed="true" type="button" data-toggle="collapse" data-target="#menu" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                @Localizer["Navbar-Menu"]
            </button>
            <vc:hero-health></vc:hero-health>
            <vc:hero-resources></vc:hero-resources>
        </div>
        <hr class="bg-primary">
        <div class="row">
            <nav class="navbar navbar-expand-lg navbar-light bg-transparent col-lg-2 col-md-12 p-0 h-100">
                <ul id="menu" class="collapse navbar-collapse list-unstyled flex-column p-1 ">
                    <h4 class="text-center text-uppercase">@Localizer["Navbar-Menu"]</h4>
                    <li class="nav-item w-100">
                        <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="" asp-controller="Hero" asp-action="Index">@Localizer["Navbar-Hero"]</a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="" asp-controller="Notifications" asp-action="Index">@Localizer["Navbar-Notifications"] <vc:new-notifications-count></vc:new-notifications-count></a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="" asp-controller="Characteristics" asp-action="Index">@Localizer["Navbar-Practice"]</a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="Village" asp-controller="Village" asp-action="Index">@Localizer["Navbar-Village"]</a>
                    </li>
                    @if (await this.LevelService.GetCurrentHeroLevel() >= RequiredLevels.DungeonRequiredLevel)
                    {
                        <li class="nav-item w-100">
                            <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="" asp-controller="Dungeon" asp-action="Index">@Localizer["Navbar-Dungeon"]</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item w-100">
                            <a class="btn btn-primary p-1 nav-link text-uppercase opacity-30" data-toggle="tooltip" data-placement="right" title="@string.Format(SharedLocalizer.ExceptionLocalizer("Level-Requirement-Instruction"), RequiredLevels.DungeonRequiredLevel)">@Localizer["Navbar-Dungeon"]</a>
                        </li>
                    }
                    <li class="nav-item w-100">
                        <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="" asp-controller="Battlefield" asp-action="Index">@Localizer["Navbar-Battlefield"]</a>
                    </li>
                    <li class="nav-item w-100">
                        <a class="btn btn-primary p-1 nav-link text-uppercase" asp-area="" asp-controller="Leaderboards" asp-action="Index">@Localizer["Navbar-Leaderboards"]</a>
                    </li>
                    <li class="nav-item w-100">
                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@(this.Url.Action("Index", "Home", new { area = string.Empty }))">
                            <button type="submit" class="btn btn-primary p-1 w-100 nav-link text-uppercase">@Localizer["Navbar-Logout"]</button>
                        </form>
                    </li>
                </ul>
            </nav>
            <div id="view-body" class="col-lg-8 col-md-12 border border-primary border-top-0 border-bottom-0 border-left-1 border-right-1">
                @if (this.TempData["ExceptionMessage"] != null)
                {
                    <div class="alert alert-danger disappearing-alert" role="alert">
                        <h4 class="alert-heading font-weight-bolder">@Localizer["Exception-Message-Header"]</h4>
                        <p class="mb-0"><span class="font-weight-bold">@SharedLocalizer.ExceptionLocalizer("Exception-Cause"): </span>@this.TempData["ExceptionMessage"]</p>
                        <p><span class="font-weight-bold">@SharedLocalizer.ExceptionLocalizer("Exception-Instructions"): </span>@this.TempData["ExceptionInstructions"]</p>
                        <hr>
                        <p class="mb-0 text-muted font-italic text-right">@Localizer["Exception-Message-Footer"]</p>
                    </div>
                }
                @if (this.TempData["Alert"] != null)
                {
                    <div class="alert alert-success disappearing-alert" role="alert">
                        <p class="text-center m-0">@this.TempData["Alert"]</p>
                    </div>
                }
                <partial name="_CookieConsentPartial" />
                @RenderBody()
            </div>
            <ul class="nav flex-column text-center p-1 col-2 d-lg-block d-none">
                <vc:side-menu-timers></vc:side-menu-timers>
                <vc:side-menu-amulets></vc:side-menu-amulets>
                <li class="nav-item">
                    <hr class="bg-primary w-75" />
                    <img src="~/images/icons/resources-side-menu-icon.png" alt="resources" class="side-menu-icon clickable img-fluid" onclick="toggleSideMenuTab('resources-side-menu')" />
                    <img src="~/images/icons/effects-side-menu-icon.png" alt="resources" class="side-menu-icon clickable img-fluid" onclick="toggleSideMenuTab('effects-side-menu')" />
                    <hr class="bg-primary w-75" />
                </li>
                <vc:side-menu-bonuses></vc:side-menu-bonuses>
                <vc:side-menu-resources></vc:side-menu-resources>
            </ul>
        </div>
        <hr class="bg-primary">
        <footer>
            <div class="row">
                <div class="col-10 text-left">
                    <h6 class="font-weight-bold">@Localizer["Created-By"] <a href="https://softuni.bg/users/profile/show/peterarnaudov" target="_blank">PeterArnaudov</a>.</h6>
                    <div>
                        <a href="https://www.instagram.com/peterxarnaudov/" target="_blank"><img src="~/images/community/instagram.png" alt="Instagram logo" class="m-2 logo"></a>
                        <a href="https://www.facebook.com/Peter.P.Arnaudov" target="_blank"><img src="~/images/community/facebook.png" alt="Facebook logo" class="m-2 logo"></a>
                        <a href="https://www.linkedin.com/in/peter-arnaudov/" target="_blank"><img src="~/images/community/linkedin.png" alt="LinkedIn logo" class="m-2 logo"></a>
                        <a href="https://github.com/PeterArnaudov/FarmHeroes" target="_blank"><img src="~/images/community/github.png" alt="Github logo" class="m-2 logo"></a>
                    </div>
                    <h6 class="font-weight-bold">@Localizer["Educational-Purpose"] <a href="https://www.botva.ru">www.botva.ru</a>.</h6>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <select id="change-language" class="form-control" name="culture" onchange="changeLanguage()">
                            <option selected>@Localizer["Choose-Language"]</option>
                            <option value="en">@Localizer["English"]</option>
                            <option value="bg">@Localizer["Bulgarian"]</option>
                        </select>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls/equipment.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls/health.js" asp-append-version="true"></script>
        <script src="~/lib/signalr/dist/browser/signalr.min.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls/equipment.js" asp-append-version="true"></script>
        <script src="~/js/ajax-calls/health.js" asp-append-version="true"></script>
        <script src="~/lib/signalr/dist/browser/signalr.min.js" asp-append-version="true"></script>
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>