FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Controllers/GameControl/MonstersController.cs
namespace FarmHeroes.Web.Areas.Administration.Controllers.GameControl
{
    using FarmHeroes.Data.Models.MonsterModels;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.ViewModels.MonsterModels;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    public class MonstersController : AdministrationController
    {
        private readonly IMonsterService monsterService;

        public MonstersController(IMonsterService monsterService)
        {
            this.monsterService = monsterService;
        }

        public async Task<IActionResult> Index()
        {
            Monster[] viewModel = await this.monsterService.GetAllMonsters();

            return this.View(viewModel);
        }

        public IActionResult Add()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(MonsterInputModel inputModel)
        {
            await this.monsterService.AddMonster(inputModel);

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            MonsterInputModel inputModel = await this.monsterService.GetMonsterInputModelById(id);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MonsterInputModel inputModel)
        {
            await this.monsterService.EditMonster(inputModel);

            return this.RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(int id)
        {
            await this.monsterService.DeleteMonster(id);

            return this.RedirectToAction("Index");
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/Monsters/Add.cshtml
@model FarmHeroes.Web.ViewModels.MonsterModels.MonsterInputModel
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<a asp-area="Administration" asp-controller="Monsters" asp-action="Index" class="btn btn-primary text-uppercase">Go Back</a>

<form asp-area="Administration" asp-controller="Monsters" asp-action="Add" method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group mt-2">
        <label asp-for="Name"></label>
        <span asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="AvatarUrl"></label>
        <span asp-validation-for="AvatarUrl" class="text-danger"></span>
        <input asp-for="AvatarUrl" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Level"></label>
        <span asp-validation-for="Level" class="text-danger"></span>
        <input asp-for="Level" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="StatPercentage"></label>
        <span asp-validation-for="StatPercentage" class="text-danger"></span>
        <input asp-for="StatPercentage" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="MinimalRewardModifier"></label>
        <span asp-validation-for="MinimalRewardModifier" class="text-danger"></span>
        <input asp-for="MinimalRewardModifier" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="MaximalRewardModifier"></label>
        <span asp-validation-for="MaximalRewardModifier" class="text-danger"></span>
        <input asp-for="MaximalRewardModifier" class="form-control">
    </div>
    <button type="submit" class="btn btn-success text-uppercase">Add Monster</button>
</form>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/Monsters/Edit.cshtml
@model FarmHeroes.Web.ViewModels.MonsterModels.MonsterInputModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<a asp-area="Administration" asp-controller="Monsters" asp-action="Index" class="btn btn-primary text-uppercase">Go Back</a>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group mt-2">
        <label asp-for="Name"></label>
        <span asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="AvatarUrl"></label>
        <span asp-validation-for="AvatarUrl" class="text-danger"></span>
        <input asp-for="AvatarUrl" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="Level"></label>
        <span asp-validation-for="Level" class="text-danger"></span>
        <input asp-for="Level" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="StatPercentage"></label>
        <span asp-validation-for="StatPercentage" class="text-danger"></span>
        <input asp-for="StatPercentage" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="MinimalRewardModifier"></label>
        <span asp-validation-for="MinimalRewardModifier" class="text-danger"></span>
        <input asp-for="MinimalRewardModifier" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="MaximalRewardModifier"></label>
        <span asp-validation-for="MaximalRewardModifier" class="text-danger"></span>
        <input asp-for="MaximalRewardModifier" class="form-control">
    </div>
    <div class="form-group d-none">
        <label asp-for="Id"></label>
        <input asp-for="Id" class="form-control">
    </div>
    <button type="submit" class="btn btn-success text-uppercase">Edit Monster</button>
</form>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/Monsters/Index.cshtml
@model FarmHeroes.Data.Models.MonsterModels.Monster[]
@{
    ViewData["Title"] = "Monsters";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<a asp-area="Administration" asp-controller="GameControl" asp-action="Index" class="btn btn-primary text-uppercase">Go Back</a>
<a asp-area="Administration" asp-controller="Monsters" asp-action="Add" class="btn btn-success float-right text-uppercase">Add Monster</a>

<table class="table mt-2">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Level</th>
            <th scope="col">Stats</th>
            <th scope="col">Min Reward Modifier</th>
            <th scope="col">Max Reward Modifier</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var monster in Model)
        {
        <tr>
            <th scope="row">@monster.Name</th>
            <td>@monster.Level</td>
            <td>@monster.StatPercentage%</td>
            <td>@monster.MinimalRewardModifier</td>
            <td>@monster.MaximalRewardModifier</td>
            <td>
                <a asp-area="Administration" asp-controller="Monsters" asp-action="Edit" asp-route-id="@monster.Id" class="btn btn-info text-uppercase">Edit</a>
                <a asp-area="Administration" asp-controller="Monsters" asp-action="Delete" asp-route-id="@monster.Id" class="btn btn-danger text-uppercase">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>