FarmHeroes/Web/FarmHeroes.Web/Areas/Village/Controllers/FarmController.cs
namespace FarmHeroes.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using FarmHeroes.Data.Models.Enums;
    using FarmHeroes.Data.Models.HeroModels;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Services.Data.Formulas;
    using FarmHeroes.Web.Filters;
    using FarmHeroes.Web.ViewModels.FarmModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Localization;

    [Authorize]
    [Area("Village")]
    public class FarmController : BaseController
    {
        private readonly IHeroService heroService;
        private readonly IFarmService farmService;
        private readonly IChronometerService chronometerService;
        private readonly IStringLocalizer<FarmController> stringLocalizer;

        public FarmController(IHeroService heroService, IFarmService farmService, IChronometerService chronometerService, IStringLocalizer<FarmController> stringLocalizer)
        {
            this.heroService = heroService;
            this.farmService = farmService;
            this.chronometerService = chronometerService;
            this.stringLocalizer = stringLocalizer;
        }

        public async Task<IActionResult> Index()
        {
            await this.heroService.ValidateCurrentHeroLocation(WorkStatus.Farm);

            FarmViewModel viewModel = await this.heroService.GetCurrentHeroViewModel<FarmViewModel>();

            return this.View(viewModel);
        }

        public async Task<IActionResult> StartWork()
        {
            int seconds = await this.farmService.StartWork();

            return this.Json(new
            {
                seconds,
                timeLeftParagraph = this.stringLocalizer["Work-Time-Left-Paragraph"].Value,
                cancelWorkParagraph = this.stringLocalizer["Cancel-Work-Paragraph"].Value,
                cancelButton = this.stringLocalizer["Cancel-Button-Text"].Value,
            });
        }

        public async Task<IActionResult> Collect()
        {
            return this.Json(await this.farmService.Collect());
        }

        public async Task<IActionResult> CancelWork()
        {
            await this.chronometerService.NullifyWorkUntil();

            int salary = FarmFormulas.CalculateFarmSalaryPerHour(this.heroService.GetHero().Result.Level.CurrentLevel);

            return this.Json(new
            {
                salary,
                salaryParagraph = this.stringLocalizer["Current-Salary-Paragraph"].Value,
                durationParagraph = this.stringLocalizer["Work-Duration-Paragraph"].Value,
                workButton = this.stringLocalizer["Work-Button-Text"].Value,
            });
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Components/TimerViewComponent.cs
namespace FarmHeroes.Web.Components
{
    using System;
    using System.Threading.Tasks;

    using FarmHeroes.Data.Models.HeroModels;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.ViewModels.ViewComponentsModels;
    using Microsoft.AspNetCore.Mvc;

    public class TimerViewComponent : ViewComponent
    {
        public TimerViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync(string domElementId, DateTime? dateTime)
        {
            TimerViewComponentModel viewModel = new TimerViewComponentModel
            {
                TimeSpan = dateTime - DateTime.UtcNow,
                DomElementId = domElementId,
            };

            if (viewModel.TimeSpan == null)
            {
                viewModel.TimeSpan = new TimeSpan(0, 0, 0);
            }

            return this.View(viewModel);
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Controllers/FarmController.cs
namespace FarmHeroes.Web.Controllers
{
    using System;
    using System.Threading.Tasks;

    using FarmHeroes.Data.Models.Enums;
    using FarmHeroes.Data.Models.HeroModels;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.Filters;
    using FarmHeroes.Web.ViewModels.FarmModels;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;

    [Authorize]
    public class FarmController : BaseController
    {
        private readonly IHeroService heroService;

        public FarmController(IHeroService heroService)
        {
            this.heroService = heroService;
        }

        public async Task<IActionResult> Index()
        {
            Hero hero = await this.heroService.GetCurrentHero();

            if (!await this.heroService.ValidateCurrentHeroLocation(WorkStatus.Farm))
            {
                return this.Redirect($"/{hero.WorkStatus}");
            }

            FarmViewModel viewModel = await this.heroService.GetCurrentHeroViewModel<FarmViewModel>();

            return this.View(viewModel);
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Areas/Village/Views/Farm/Index.cshtml
@model FarmHeroes.Web.ViewModels.FarmModels.FarmViewModel
@{
    ViewData["Title"] = "Farm";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<div class="text-center">
    <img src="~/images/village/farm/farm.jpg" alt="village-image" class="d-block img-fluid ml-auto mr-auto mb-3">
    <div id="work-body">
        @if (!Model.DoesWork)
        {
            <p>@Localizer["Current-Salary-Paragraph"] @Model.Salary.ToString("N0") <img src="~/images/icons/gold-icon.png" alt="gold" class="icon">.</p>
            <p>@Localizer["Work-Duration-Paragraph"]</p>
            <button onclick="startWork()" class="btn btn-primary text-uppercase">@Localizer["Work-Button-Text"]</button>
        }
        else
        {
            if (Model.IsWorkFinished)
            {
                <p class="text-success">@Localizer["Work-Finished-Paragraph"]</p>
                <button class="btn btn-success text-uppercase" onclick="collect()">@Localizer["Collect-Button-Text"]</button>
            }
            else
            {
                <p class="mb-1">@Localizer["Work-Time-Left-Paragraph"]</p>
                <vc:timer dom-element-id="work_1" date-time="@Model.ChronometerWorkUntil"></vc:timer>
                <p class="text-danger">@Localizer["Cancel-Work-Paragraph"]</p>
                <button class="btn btn-danger text-uppercase" onclick="cancelWork()">@Localizer["Cancel-Button-Text"]</button>
            }
        }
    </div>
</div>

<script src="~/js/ajax-calls/farm.js" asp-append-version="true"></script>