FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Controllers/PlayerControlController.cs
namespace FarmHeroes.Web.Areas.Administration.Controllers
{
    using FarmHeroes.Data.Models.HeroModels;
    using FarmHeroes.Services.Data.Contracts;
    using FarmHeroes.Web.ViewModels.CharacteristcsModels;
    using FarmHeroes.Web.ViewModels.ChronometerModels;
    using FarmHeroes.Web.ViewModels.HealthModels;
    using FarmHeroes.Web.ViewModels.HeroModels;
    using FarmHeroes.Web.ViewModels.LevelModels;
    using FarmHeroes.Web.ViewModels.ResourcePouchModels;
    using FarmHeroes.Web.ViewModels.UserModels;
    using Microsoft.AspNetCore.Mvc;
    using System;
    using System.Threading.Tasks;

    public class PlayerControlController : AdministrationController
    {
        private readonly IUserService userService;
        private readonly IHeroService heroService;
        private readonly ILevelService levelService;
        private readonly IHealthService healthService;
        private readonly IResourcePouchService resourcePouchService;
        private readonly ICharacteristicsService characteristicsService;
        private readonly IChronometerService chronometerService;

        public PlayerControlController(IUserService userService, IHeroService heroService, ILevelService levelService, IHealthService healthService, IResourcePouchService resourcePouchService, ICharacteristicsService characteristicsService, IChronometerService chronometerService)
        {
            this.userService = userService;
            this.heroService = heroService;
            this.levelService = levelService;
            this.healthService = healthService;
            this.resourcePouchService = resourcePouchService;
            this.characteristicsService = characteristicsService;
            this.chronometerService = chronometerService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Ban()
        {
            return this.View();
        }

        [HttpPost]
        public async Task<IActionResult> Ban(BanInputModel inputModel)
        {
            await this.userService.BanUserByUsername(inputModel);
            return this.RedirectToAction("Ban");
        }

        public IActionResult Roles()
        {
            return this.View();
        }

        [Route("/{area}/{controller}/{action}/{roleName}")]
        public IActionResult ModifyRole(string roleName)
        {
            return this.View("ModifyRole", roleName);
        }

        [HttpPost]
        public async Task<IActionResult> Promote(string username, string roleName)
        {
            await this.userService.AddUserToRole(username, roleName);

            return this.Redirect(this.HttpContext.Request.Headers["Referer"]);
        }

        public async Task<IActionResult> Demote(string username, string roleName)
        {
            await this.userService.RemoveUserFromRole(username, roleName);

            return this.Redirect(this.HttpContext.Request.Headers["Referer"]);
        }

        public IActionResult FindHero()
        {
            return this.View();
        }

        public async Task<IActionResult> ModifyHero(string name)
        {
            await this.userService.CheckIfUserExists(name);

            return this.View("ModifyHero", name);
        }

        public async Task<IActionResult> ModifyBasicInfo(string name)
        {
            await this.userService.CheckIfUserExists(name);

            HeroModifyBasicInfoInputModel inputModel = await this.heroService.GetHeroViewModelByName<HeroModifyBasicInfoInputModel>(name);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyBasicInfo(HeroModifyBasicInfoInputModel inputModel)
        {
            await this.userService.CheckIfUserExists(inputModel.Name);

            await this.heroService.UpdateBasicInfo(inputModel);

            return this.RedirectToAction("ModifyHero", new { inputModel.Name });
        }

        public async Task<IActionResult> ModifyLevel(string name)
        {
            await this.userService.CheckIfUserExists(name);

            LevelModifyInputModel inputModel = await this.heroService.GetHeroViewModelByName<LevelModifyInputModel>(name);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyLevel(LevelModifyInputModel inputModel)
        {
            await this.userService.CheckIfUserExists(inputModel.Name);

            await this.levelService.UpdateLevel(inputModel);

            return this.RedirectToAction("ModifyHero", new { inputModel.Name });
        }

        public async Task<IActionResult> ModifyHealth(string name)
        {
            await this.userService.CheckIfUserExists(name);

            HealthModifyInputModel inputModel = await this.heroService.GetHeroViewModelByName<HealthModifyInputModel>(name);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyHealth(HealthModifyInputModel inputModel)
        {
            await this.userService.CheckIfUserExists(inputModel.Name);

            await this.healthService.UpdateHealth(inputModel);

            return this.RedirectToAction("ModifyHero", new { inputModel.Name });
        }

        public async Task<IActionResult> ModifyResourcePouch(string name)
        {
            await this.userService.CheckIfUserExists(name);

            ResourcePouchModifyInputModel inputModel = await this.heroService.GetHeroViewModelByName<ResourcePouchModifyInputModel>(name);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyResourcePouch(ResourcePouchModifyInputModel inputModel)
        {
            await this.userService.CheckIfUserExists(inputModel.Name);

            await this.resourcePouchService.UpdateResourcePouch(inputModel);

            return this.RedirectToAction("ModifyHero", new { inputModel.Name });
        }

        public async Task<IActionResult> ModifyCharacteristics(string name)
        {
            await this.userService.CheckIfUserExists(name);

            CharacteristicsModifyInputModel inputModel = await this.heroService.GetHeroViewModelByName<CharacteristicsModifyInputModel>(name);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyCharacteristics(CharacteristicsModifyInputModel inputModel)
        {
            await this.userService.CheckIfUserExists(inputModel.Name);

            await this.characteristicsService.UpdateCharacteristics(inputModel);

            return this.RedirectToAction("ModifyHero", new { inputModel.Name });
        }

        public async Task<IActionResult> ModifyChronometer(string name)
        {
            await this.userService.CheckIfUserExists(name);

            ChronometerModifyInputModel inputModel = await this.heroService.GetHeroViewModelByName<ChronometerModifyInputModel>(name);

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> ModifyChronometer(ChronometerModifyInputModel inputModel)
        {
            await this.userService.CheckIfUserExists(inputModel.Name);

            await this.chronometerService.UpdateChronometer(inputModel);

            return this.RedirectToAction("ModifyHero", new { inputModel.Name });
        }
    }
}

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/Ban.cshtml
@model FarmHeroes.Web.ViewModels.UserModels.BanInputModel
@{
    ViewData["Title"] = "Ban";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<p>Fill the form below to ban someone. If you want to unban him - set it to a past time.</p>
<form asp-action="Ban">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <div class="form-group">
            <label asp-for="Username"></label>
            <input asp-for="Username" class="form-control" />
            <span asp-validation-for="Username" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="BanUntil"></label>
        <input asp-for="BanUntil" class="form-control" placeholder="dd.MM.yyyy hh:mm" />
        <span asp-validation-for="BanUntil" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-danger text-uppercase">Ban</button>
</form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Index">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/FindHero.cshtml
@{
    ViewData["Title"] = "Find Hero";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<p>Enter the desired username and press the button.</p>
<form asp-action="ModifyHero">
    <div class="form-group">
        <label for="name">Username</label>
        <input name="name" class="form-control" />
    </div>
    <button type="submit" class="btn btn-primary text-uppercase">Modify Hero</button>
</form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Index">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/Index.cshtml
@{
    ViewData["Title"] = "Player Control";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<div class="row">
    <a class="col-4 btn btn-outline-primary border-left-0 border-right-0 nav-link text-uppercase" asp-area="Administration" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
    <a class="col-4 btn btn-outline-primary nav-link disabled text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Index">Player control</a>
    <a class="col-4 btn btn-outline-primary border-left-0 border-right-0 nav-link text-uppercase" asp-area="Administration" asp-controller="GameControl" asp-action="Index">Game control</a>
</div>
<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Ban">Ban</a>
<a class="btn btn-block btn-primary text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Roles">Roles</a>
<a class="btn btn-block btn-primary text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="FindHero">Modify Heroes</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyBasicInfo.cshtml
@model FarmHeroes.Web.ViewModels.HeroModels.HeroModifyBasicInfoInputModel
@{
    ViewData["Title"] = "Modify Basic Info";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<form asp-action="ModifyBasicInfo">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group d-none">
        <label asp-for="Name">Name</label>
        <input asp-for="Name">
    </div>
    <label asp-for="Gender">Gender</label>
    <select asp-for="Gender" class="form-control form-control-sm" asp-items="@Html.GetEnumSelectList<FarmHeroes.Data.Models.Enums.Gender>()">
    </select>
    <span asp-validation-for="Gender" class="text-danger"></span>
    <label asp-for="Fraction">Fraction</label>
    <select asp-for="Fraction" class="form-control form-control-sm" asp-items="@Html.GetEnumSelectList<FarmHeroes.Data.Models.Enums.Fraction>()">
    </select>
    <span asp-validation-for="Fraction" class="text-danger"></span>
    <button type="submit" class="btn btn-primary btn-block mt-3 text-uppercase">Modify</button>
</form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHero" asp-route-name="@Model.Name">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyCharacteristics.cshtml
@model FarmHeroes.Web.ViewModels.CharacteristcsModels.CharacteristicsModifyInputModel
@{
    ViewData["Title"] = "Modify Characteristics";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

    <form asp-action="ModifyCharacteristics">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group d-none">
            <label asp-for="Name">Name</label>
            <input asp-for="Name">
        </div>
        <div class="form-group">
            <label asp-for="CharacteristicsAttack">Attack</label>
            <input asp-for="CharacteristicsAttack">
        </div>
        <div class="form-group">
            <label asp-for="CharacteristicsDefense">Defense</label>
            <input asp-for="CharacteristicsDefense">
        </div>
        <div class="form-group">
            <label asp-for="CharacteristicsMastery">Mastery</label>
            <input asp-for="CharacteristicsMastery">
        </div>
        <div class="form-group">
            <label asp-for="CharacteristicsMass">Mass</label>
            <input asp-for="CharacteristicsMass">
        </div>
        <div class="form-group">
            <label asp-for="CharacteristicsDexterity">Dexterity</label>
            <input asp-for="CharacteristicsDexterity">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-3 text-uppercase">Modify</button>
    </form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHero" asp-route-name="@Model.Name">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyChronometer.cshtml
@model FarmHeroes.Web.ViewModels.ChronometerModels.ChronometerModifyInputModel
@{
    ViewData["Title"] = "Modify Level";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

    <form asp-action="ModifyChronometer">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group d-none">
            <label asp-for="Name">Name</label>
            <input asp-for="Name">
        </div>
        <div class="form-group">
            <label asp-for="ChronometerWorkUntil">Work until</label>
            <input asp-for="ChronometerWorkUntil">
            <small class="form-text text-muted">Leave blank to cancel the hero's current work.</small>
        </div>
        <div class="form-group">
            <label asp-for="ChronometerCannotAttackHeroUntil">Cannot attack hero until</label>
            <input asp-for="ChronometerCannotAttackHeroUntil">
        </div>
        <div class="form-group">
            <label asp-for="ChronometerCannotBeAttackedUntil">Defense until</label>
            <input asp-for="ChronometerCannotBeAttackedUntil">
        </div>
        <div class="form-group">
            <label asp-for="ChronometerCannotAttackMonsterUntil">Cannot attack monster until</label>
            <input asp-for="ChronometerCannotAttackMonsterUntil">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-3 text-uppercase">Modify</button>
    </form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHero" asp-route-name="@Model.Name">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyHealth.cshtml
@model FarmHeroes.Web.ViewModels.HealthModels.HealthModifyInputModel
@{
    ViewData["Title"] = "Modify Health";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<form asp-action="ModifyHealth">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group d-none">
        <label asp-for="Name">Name</label>
        <input asp-for="Name">
    </div>
    <div class="form-group">
        <label asp-for="HealthCurrent">Current Health</label>
        <input asp-for="HealthCurrent">
    </div>
    <div class="form-group">
        <label asp-for="HealthMaximum">Maximum Health</label>
        <input asp-for="HealthMaximum">
    </div>
    <button type="submit" class="btn btn-primary btn-block mt-3 text-uppercase">Modify</button>
</form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHero" asp-route-name="@Model.Name">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyHero.cshtml
@model string
@{
    ViewData["Title"] = "Modify Hero";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyBasicInfo" asp-route-name="@Model">Basic Info</a>
<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyLevel" asp-route-name="@Model">Level</a>
<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHealth" asp-route-name="@Model">Health</a>
<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyResourcePouch" asp-route-name="@Model">Resources</a>
<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyCharacteristics" asp-route-name="@Model">Characteristics</a>
<a class="btn btn-block btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyChronometer" asp-route-name="@Model">Timers</a>

<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="FindHero">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyLevel.cshtml
@model FarmHeroes.Web.ViewModels.LevelModels.LevelModifyInputModel
@{
    ViewData["Title"] = "Modify Level";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

    <form asp-action="ModifyLevel">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group d-none">
            <label asp-for="Name">Name</label>
            <input asp-for="Name">
        </div>
        <div class="form-group">
            <label asp-for="LevelCurrentLevel">Level</label>
            <input asp-for="LevelCurrentLevel">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-3 text-uppercase">Modify</button>
    </form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHero" asp-route-name="@Model.Name">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyResourcePouch.cshtml
@model FarmHeroes.Web.ViewModels.ResourcePouchModels.ResourcePouchModifyInputModel
@{
    ViewData["Title"] = "Modify Resources";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<form asp-action="ModifyResourcePouch">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group d-none">
        <label asp-for="Name">Name</label>
        <input asp-for="Name">
    </div>
    <div class="form-group">
        <label asp-for="ResourcePouchGold">Gold</label>
        <input asp-for="ResourcePouchGold">
    </div>
    <div class="form-group">
        <label asp-for="ResourcePouchCrystals">Crystals</label>
        <input asp-for="ResourcePouchCrystals">
    </div>
    <button type="submit" class="btn btn-primary btn-block mt-3 text-uppercase">Modify</button>
</form>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyHero" asp-route-name="@Model.Name">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/ModifyRole.cshtml
@model string
@inject Microsoft.AspNetCore.Identity.UserManager<FarmHeroes.Data.Models.ApplicationUser> UserManager
@{
    ViewData["Title"] = "Modify Role";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<h1>@Model - Users: @this.UserManager.GetUsersInRoleAsync(Model).Result.Count</h1>
<p>To add user to this role, enter their username below and press the button.</p>
<form asp-action="Promote">
    <div class="form-group">
        <label for="username">Username</label>
        <input name="username" class="form-control" />
    </div>
    <div class="form-group d-none">
        <label for="roleName">Role</label>
        <input class="form-control" name="roleName" value="@Model" />
    </div>
    <button type="submit" class="btn btn-primary text-uppercase">Add to role</button>
</form>
<table class="table table-hover mt-3">
    <thead>
        <tr>
            <th scope="col">Username</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in this.UserManager.GetUsersInRoleAsync(Model).Result)
        {
            <tr>
                <td>@user.UserName</td>
                <td><a asp-area="Administration" asp-controller="PlayerControl" asp-action="Demote" asp-route-roleName="@Model" asp-route-username="@user.UserName" class="btn btn-danger text-uppercase">Demote</a></td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Roles">Go Back</a>

FarmHeroes/Web/FarmHeroes.Web/Areas/Administration/Views/PlayerControl/Roles.cshtml
@inject Microsoft.AspNetCore.Identity.RoleManager<FarmHeroes.Data.Models.ApplicationRole> RoleManager
@inject Microsoft.AspNetCore.Identity.UserManager<FarmHeroes.Data.Models.ApplicationUser> UserManager
@{
    ViewData["Title"] = "Roles";
    Layout = "~/Views/Shared/_LoggedLayout.cshtml";
}

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Users</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in this.RoleManager.Roles)
        {
            <tr>
                <td>@role.Name</td>
                <td>@this.UserManager.GetUsersInRoleAsync(role.Name).Result.Count</td>
                <td><a asp-area="Administration" asp-controller="PlayerControl" asp-action="ModifyRole" asp-route-roleName="@role.Name" class="btn btn-primary text-uppercase">Modify</a></td>
            </tr>
        }
    </tbody>
</table>
<a class="btn btn-primary mt-3 text-uppercase" asp-area="Administration" asp-controller="PlayerControl" asp-action="Index">Go Back</a>